### PR TITLE
Added some extra Documentation

### PR DESCRIPTION
**Pull request by bornikfik**

### CODE REVIEW

**Comment by TheTurkeyDev** [comment]
Only thing I'm noticing is that a lot of your changes are changing from 4 spaces as indents to 2 spaces. The linter is setup to 4 spaces

**Comment by itsjusttriz** [comment]
@TheTurkeyDev Pretty sure your eslint & vsc should auto-format back to 4 spaces on save. So technically, you could merge, reopen, reformat, then repush 🤷🏼

**Comment by TheTurkeyDev** [comment]
Yes, but that's not the ideal way to do it xD I also just want to make sure the eslint rule and everything are working as it should be complaining about the 2 space indentation. The whole point of eslint is to not have these issues in the first place

**Comment by itsjusttriz** [comment]
fair :)

**Comment by bornikfik** [comment]
i have my prettier setup for 2 spaces instead of 4 ill fix it soon

**Pull request merged**
