### PR TITLE
Add example to README

### PR DESCRIPTION
**Pull request by fxiqval**
I added an example bot to the README.md

### CODE REVIEW

**Comment by TheTurkeyDev** [comment]
Probably better off to have like an "examples" folder, but we can have a very simplistic one in the readme. The token should be left out though

**Comment by fxiqval** [comment]
also i changed the token system, i have no idea how pull requests work so if i messed anything up, i'm sorry.
by the way the token is already regenerated

**Comment by TheTurkeyDev** [comment]
Also it seems you have committed a lot more than just this and should not be included in this PR

**Comment by TheTurkeyDev** [comment]
> also i changed the token system, i have no idea how pull requests work so if i messed anything up, i'm sorry.
> by the way the token is already regenerated

Yeah this is probably best off to be done with a separate PR. If you need you can close this one and make a new one for each of the two things you want added

**Pull request closed without merging**
